model:
  type: efficientnet-b0
dataset: imagenet
aug: fa_reduced_imagenet
cutout: 0
batch: 128    # per gpu
epoch: 360
lr: 0.008     # 0.256 for 4096 batch
lr_schedule:
  type: 'efficientnet'
  warmup:
    multiplier: 1
    epoch: 10
optimizer:
  type: rmsprop
  decay: 0.00001
  clip: 0
  ema: 0.9999
lb_smooth: 0.1
